# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: Lucash Sanjivala
# Version: 2.1
# Company: LSoft Corporation
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(505, 427)
        Cadastro.setMinimumSize(QtCore.QSize(505, 427))
        Cadastro.setMaximumSize(QtCore.QSize(505, 427))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files/Hand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cadastro.setWindowIcon(icon)
        Cadastro.setStyleSheet(
            "background: qconicalgradient(cx:0.5, cy:0.483, angle:0, stop:0 rgba(69, 77, 14, 255), stop:0.16 rgba("
            "136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 "
            "rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), "
            "stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, "
            "255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, "
            "51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255))")
        self.centralwidget = QtWidgets.QWidget(Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 70, 491, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.txtTexto = QtWidgets.QTextEdit(self.centralwidget)
        self.txtTexto.setGeometry(QtCore.QRect(10, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txtTexto.setFont(font)
        self.txtTexto.setStyleSheet(
            "background: #f4f4f4;color: #333;border-radius: 5px;border: 1px solid #333;padding: 5px;")
        self.txtTexto.setObjectName("txtTexto")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 90, 16, 311))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.txtCapitulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCapitulo.setGeometry(QtCore.QRect(10, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCapitulo.setFont(font)
        self.txtCapitulo.setStyleSheet("background: #ddd;color: #333;border-radius: 5px;border: 1px solid #333;")
        self.txtCapitulo.setMaxLength(3)
        self.txtCapitulo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtCapitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCapitulo.setObjectName("txtCapitulo")
        self.txtVersiculo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVersiculo.setGeometry(QtCore.QRect(160, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.txtVersiculo.setFont(font)
        self.txtVersiculo.setStyleSheet("background: #ddd;color: #333;border-radius: 5px;border: 1px solid #333;")
        self.txtVersiculo.setMaxLength(3)
        self.txtVersiculo.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVersiculo.setObjectName("txtVersiculo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-family: Comic Sans MS;\ncolor: #fff;")
        self.label_2.setObjectName("label_2")
        self.btnGravar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGravar.setGeometry(QtCore.QRect(270, 330, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnGravar.setFont(font)
        self.btnGravar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGravar.setStyleSheet("QPushButton {border-radius: 10px;background: #786314;border: 1px solid #333;\n"
                                     "color: #f9f9f9;}\nQPushButton:hover {background: #A6C8FC;color: #333;}")
        self.btnGravar.setObjectName("btnGravar")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(270, 300, 231, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(384, 330, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCancelar.setAutoFillBackground(False)
        self.btnCancelar.setStyleSheet("QPushButton {border-radius: 10px;background: #786314;border: 1px solid #333;\n"
                                       "color: #f9f9f9;}\nQPushButton:hover {background: #A6C8FC;color: #333;}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setGeometry(QtCore.QRect(270, 372, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnLimpar.setFont(font)
        self.btnLimpar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLimpar.setStyleSheet("QPushButton {border-radius: 10px;background: #786314;border: 1px solid #333;\n"
                                     "color: #f9f9f9;}\nQPushButton:hover {background: #A6C8FC;color: #333;}")
        self.btnLimpar.setObjectName("btnLimpar")
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setGeometry(QtCore.QRect(384, 372, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btnSair.setFont(font)
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("QPushButton {border-radius: 10px;background: #786314;border: 1px solid #333;\n"
                                   "color: #f9f9f9;}\nQPushButton:hover {background: #A6C8FC;color: #333;}")
        self.btnSair.setObjectName("btnSair")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 90, 231, 121))
        self.label_3.setStyleSheet("background: #fff;\ncolor: #333;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("files/Bíblia Sagrada.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 220, 231, 81))
        self.label_4.setStyleSheet("background: rgba(255, 255, 255, .3);color: #333;border-radius: 5px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.cbLivros = QtWidgets.QComboBox(self.centralwidget)
        self.cbLivros.setGeometry(QtCore.QRect(10, 370, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbLivros.setFont(font)
        self.cbLivros.setStyleSheet("color: #333;\nborder: none;\nborder-radius: 5px;\npadding: 0 7px;")
        self.cbLivros.setObjectName("cbLivros")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        self.cbLivros.addItem("")
        Cadastro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Cadastro)
        self.statusbar.setObjectName("statusbar")
        Cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)

        self.btnLimpar.clicked.connect(self.limpar)
        self.btnCancelar.clicked.connect(self.cancelar)
        self.btnGravar.clicked.connect(self.gravar)
        self.btnSair.clicked.connect(self.sair)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "Cadastro"))
        self.label.setText(_translate("Cadastro",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#ffffff;\">Cadastro de Versículos</span></p></body></html>"))
        self.txtTexto.setPlaceholderText(_translate("Cadastro", "Escreva aqui o texto"))
        self.txtCapitulo.setPlaceholderText(_translate("Cadastro", "Capítulo"))
        self.txtVersiculo.setPlaceholderText(_translate("Cadastro", "Versículo"))
        self.label_2.setText(_translate("Cadastro",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Cadastrar Aqui</span></p></body></html>"))
        self.btnGravar.setText(_translate("Cadastro", "Gravar"))
        self.btnCancelar.setText(_translate("Cadastro", "Cancelar"))
        self.btnLimpar.setText(_translate("Cadastro", "Limpar"))
        self.btnSair.setText(_translate("Cadastro", "Sair"))
        self.label_4.setText(_translate("Cadastro",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Aquele pois que sabe fazer o bem e o não faz, comete pecado.</span></p><p align=\"right\"><span style=\" font-size:10pt; color:#ffffff;\">Tiago 4:17</span></p></body></html>"))
        self.cbLivros.setItemText(0, _translate("Cadastro", "Gênesis"))
        self.cbLivros.setItemText(1, _translate("Cadastro", "Êxodo"))
        self.cbLivros.setItemText(2, _translate("Cadastro", "Levítico"))
        self.cbLivros.setItemText(3, _translate("Cadastro", "Números"))
        self.cbLivros.setItemText(4, _translate("Cadastro", "Deuterenómio"))
        self.cbLivros.setItemText(5, _translate("Cadastro", "Josué"))
        self.cbLivros.setItemText(6, _translate("Cadastro", "Juízes"))
        self.cbLivros.setItemText(7, _translate("Cadastro", "Rute"))
        self.cbLivros.setItemText(8, _translate("Cadastro", "I Samuel"))
        self.cbLivros.setItemText(9, _translate("Cadastro", "II Samuel"))
        self.cbLivros.setItemText(10, _translate("Cadastro", "I Reis"))
        self.cbLivros.setItemText(11, _translate("Cadastro", "II Reis"))
        self.cbLivros.setItemText(12, _translate("Cadastro", "I Crónicas"))
        self.cbLivros.setItemText(13, _translate("Cadastro", "II Crónicas"))
        self.cbLivros.setItemText(14, _translate("Cadastro", "Esdras"))
        self.cbLivros.setItemText(15, _translate("Cadastro", "Neemias"))
        self.cbLivros.setItemText(16, _translate("Cadastro", "Ester"))
        self.cbLivros.setItemText(17, _translate("Cadastro", "Job"))
        self.cbLivros.setItemText(18, _translate("Cadastro", "Salmos"))
        self.cbLivros.setItemText(19, _translate("Cadastro", "Provérbios"))
        self.cbLivros.setItemText(20, _translate("Cadastro", "Eclesiastes"))
        self.cbLivros.setItemText(21, _translate("Cadastro", "Cantares de Salomão"))
        self.cbLivros.setItemText(22, _translate("Cadastro", "Isaías"))
        self.cbLivros.setItemText(23, _translate("Cadastro", "Jeremias"))
        self.cbLivros.setItemText(24, _translate("Cadastro", "Lamentações"))
        self.cbLivros.setItemText(25, _translate("Cadastro", "Ezequiel"))
        self.cbLivros.setItemText(26, _translate("Cadastro", "Daniel"))
        self.cbLivros.setItemText(27, _translate("Cadastro", "Oséias"))
        self.cbLivros.setItemText(28, _translate("Cadastro", "Joel"))
        self.cbLivros.setItemText(29, _translate("Cadastro", "Amós"))
        self.cbLivros.setItemText(30, _translate("Cadastro", "Obadias"))
        self.cbLivros.setItemText(31, _translate("Cadastro", "Jonas"))
        self.cbLivros.setItemText(32, _translate("Cadastro", "Miquéias"))
        self.cbLivros.setItemText(33, _translate("Cadastro", "Naúm"))
        self.cbLivros.setItemText(34, _translate("Cadastro", "Habacuque"))
        self.cbLivros.setItemText(35, _translate("Cadastro", "Sofonias"))
        self.cbLivros.setItemText(36, _translate("Cadastro", "Ageu"))
        self.cbLivros.setItemText(37, _translate("Cadastro", "Zacarias"))
        self.cbLivros.setItemText(38, _translate("Cadastro", "Malaquias"))
        self.cbLivros.setItemText(39, _translate("Cadastro", "----------------------------"))
        self.cbLivros.setItemText(40, _translate("Cadastro", "Mateus"))
        self.cbLivros.setItemText(41, _translate("Cadastro", "Marcos"))
        self.cbLivros.setItemText(42, _translate("Cadastro", "Lucas"))
        self.cbLivros.setItemText(43, _translate("Cadastro", "João"))
        self.cbLivros.setItemText(44, _translate("Cadastro", "Atos dos Apóstolos"))
        self.cbLivros.setItemText(45, _translate("Cadastro", "Romanos"))
        self.cbLivros.setItemText(46, _translate("Cadastro", "I Coríntios"))
        self.cbLivros.setItemText(47, _translate("Cadastro", "II Coríntios"))
        self.cbLivros.setItemText(48, _translate("Cadastro", "Gálatas"))
        self.cbLivros.setItemText(49, _translate("Cadastro", "Efésios"))
        self.cbLivros.setItemText(50, _translate("Cadastro", "Filipenses"))
        self.cbLivros.setItemText(51, _translate("Cadastro", "Colossenses"))
        self.cbLivros.setItemText(52, _translate("Cadastro", "I Tessalonicenses"))
        self.cbLivros.setItemText(53, _translate("Cadastro", "II Tessalonicenses"))
        self.cbLivros.setItemText(54, _translate("Cadastro", "I Timóteo"))
        self.cbLivros.setItemText(55, _translate("Cadastro", "II Timóteo"))
        self.cbLivros.setItemText(56, _translate("Cadastro", "Tito"))
        self.cbLivros.setItemText(57, _translate("Cadastro", "Filemon"))
        self.cbLivros.setItemText(58, _translate("Cadastro", "Hebreus"))
        self.cbLivros.setItemText(59, _translate("Cadastro", "Tiago"))
        self.cbLivros.setItemText(60, _translate("Cadastro", "I Pedro"))
        self.cbLivros.setItemText(61, _translate("Cadastro", "II Pedro"))
        self.cbLivros.setItemText(62, _translate("Cadastro", "I João"))
        self.cbLivros.setItemText(63, _translate("Cadastro", "II João"))
        self.cbLivros.setItemText(64, _translate("Cadastro", "III João"))
        self.cbLivros.setItemText(65, _translate("Cadastro", "Judas"))
        self.cbLivros.setItemText(66, _translate("Cadastro", "Apocalipse"))

    def mensagem(self, titulo, mensagem):
        alerta = QtWidgets.QMessageBox()
        alerta.setIcon(QtWidgets.QMessageBox.Warning)
        alerta.setWindowTitle(titulo)
        alerta.setText(mensagem)
        alerta.setStandardButtons(QtWidgets.QMessageBox.Ok)
        alerta.exec_()

    def alerta(self):
        sair = QtWidgets.QMessageBox()
        sair.setIcon(QtWidgets.QMessageBox.Warning)
        icone = QtGui.QIcon()
        icone.addPixmap(QtGui.QPixmap('files/Hand.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sair.setWindowIcon(icone)
        sair.setWindowTitle('Saindo...')
        sair.setText('Encerrando aplicação...')
        sair.standardButtons()
        sair.exec_()
        QtWidgets.QApplication.exit(0)

    def sucesso(self):
        feito = QtWidgets.QMessageBox()
        feito.setIcon(QtWidgets.QMessageBox.Information)
        icone = QtGui.QIcon()
        icone.addPixmap(QtGui.QPixmap('files/Hand.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        feito.setWindowIcon(icone)
        feito.setWindowTitle('Feito')
        feito.setText('Cadastro feito com sucesso...')
        feito.standardButtons()
        feito.exec_()

    def limpar(self):
        if self.txtTexto.setText != "" or self.txtCapitulo.setText != "" or self.txtVersiculo.setText != "":
            # self.cbLivros.setCurrentText('Gênesis')
            self.txtTexto.setText("")
            self.txtCapitulo.setText('')
            self.txtVersiculo.setText('')
            self.txtTexto.setFocus()
        else:
            print('Erro ao limpar')

    def cancelar(self):
        self.cbLivros.setCurrentText('Gênesis')
        self.txtTexto.setText("")
        self.txtCapitulo.setText("")
        self.txtVersiculo.setText("")
        self.txtCapitulo.setText('')
        self.txtVersiculo.setText('')
        self.txtTexto.setFocus()

    def gravar(self):

        self.texto = self.txtTexto.toPlainText()
        self.capitulo = int(self.txtCapitulo.text())
        self.versiculo = int(self.txtVersiculo.text())
        self.livro = self.cbLivros.currentText()

        ficheiro = open('versiculos.txt', 'a')

        if self.texto == '' or len(self.texto) < 20:
            self.txtVersiculo.setText('')
            self.txtCapitulo.setText('')
            self.mensagem('Texto', 'Texto demasiado curto!')
            self.txtTexto.setFocus()
        elif self.capitulo < 1 or self.capitulo > 150 or self.capitulo == "":
            print('Erro ao cadastrar capítulo!')
            self.mensagem('Capítulo', 'Cápitulo Inválido!')
            self.txtCapitulo.setText('')
            self.txtCapitulo.setFocus()
        elif self.versiculo < 1 or self.versiculo > 176 or self.versiculo == "":
            print('Erro ao cadastrar versículo!')
            self.mensagem('Versículo', 'Versículo Inválido!')
            self.txtVersiculo.setText('')
            self.txtVersiculo.setFocus()
        elif self.livro == '----------------------------':
            self.mensagem('Livro', 'Livro inválido!')
        else:
            ficheiro.write(str(self.texto) + ' -> ' + str(self.livro) + ' ' + str(self.capitulo) + ':' + str(self.versiculo) + '\n')
            print('Cadastrado com sucesso...')
            self.sucesso()
            self.limpar()

        ficheiro.close()

    def sair(self):
        # self.mensagem('Sair', 'O Sistema será encerrado!')
        # QtWidgets.QApplication.exit(0)
        self.alerta()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QMainWindow()
    ui = Ui_Cadastro()
    ui.setupUi(Cadastro)
    Cadastro.show()
    sys.exit(app.exec_())
